### ISSUE TITLE
Running query leaves behind -shm and -wal files after clean shutdown.

### ISSUE THREAD

**Issue by smoyergh** [journeyapps/sqlite_async.dart#11]
The trivial program below opens/creates a DB file, runs a query on sqlite_schema, closes the DB file, and exits. After exit it leaves behind '-shm' and '-wal' files which shouldn't happen on a clean shutdown.

If you comment-out the query and un-comment the create table command then there is no '-shm' or '-wal' after exit.

```dart
import 'package:sqlite_async/sqlite_async.dart';

Future<void> main() async {
  final db = SqliteDatabase(path: 'txntest.db');
  await db.initialize();

  await db.getAll("SELECT * FROM sqlite_schema;");

  //await db.execute("CREATE TABLE table1 (name TEXT UNIQUE NOT NULL);");

  await db.close();
}
```

**Comment by jeremylcarter** [comment]
You can change to default sqlite behavior which is journal mode delete. 
```
return SqliteDatabase(
        path: "my.db",
        options: const SqliteOptions(
            journalMode: SqliteJournalMode.delete));
```
