### ISSUE TITLE
can't get it to run on android! 

### ISSUE THREAD

**Issue by tiwwwi** [journeyapps/sqlite_async.dart#15]
I can't get this to run on android emulator.   I'm basically testing with just the code from the basic example in my flutter app. same app works great on linux  but on android emulator I get the following: 
`Using hardware rendering with device sdk gphone x86. If you notice graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib/main.dart on sdk gphone x86 in debug mode...
Running Gradle task 'assembleDebug'...                              3.0s
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
E/flutter (10609): [ERROR:flutter/runtime/dart_isolate.cc(1097)] Unhandled exception:
E/flutter (10609): SqliteException(14): while opening the database, bad parameter or other API misuse, bad parameter or other API misuse (code 21)
E/flutter (10609): #0      Sqlite3Implementation.open (package:sqlite3/src/implementation/sqlite3.dart:57:7)
E/flutter (10609): #1      FfiSqlite3.open (package:sqlite3/src/ffi/implementation.dart:33:18)
E/flutter (10609): #2      DefaultSqliteOpenFactory.open (package:sqlite_async/src/sqlite_open_factory.dart:52:29)
E/flutter (10609): #3      _sqliteConnectionIsolate (package:sqlite_async/src/sqlite_connection_impl.dart:229:39)
E/flutter (10609): #4      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:17)
E/flutter (10609): #5      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
E/flutter (10609): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Instance of 'ClosedException'
E/flutter (10609): 
E/flutter (10609): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Instance of 'ClosedException'
E/flutter (10609): 
E/flutter (10609): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Instance of 'ClosedException'
E/flutter (10609): #0      ParentPortClient.post (package:sqlite_async/src/port_channel.dart:77:7)
E/flutter (10609): #1      _TransactionContext.close (package:sqlite_async/src/sqlite_connection_impl.dart:201:21)
E/flutter (10609): #2      SqliteConnectionImpl.writeLock.<anonymous closure>.<anonymous closure> (package:sqlite_async/src/sqlite_connection_impl.dart:126:21)
E/flutter (10609): <asynchronous suspension>
E/flutter (10609): #3      SimpleMutex.lock.<anonymous closure> (package:sqlite_async/src/mutex.dart:71:16)
E/flutter (10609): <asynchronous suspension>
E/flutter (10609): #4      SqliteConnectionImpl.writeLock.<anonymous closure> (package:sqlite_async/src/sqlite_connection_impl.dart:121:14)
E/flutter (10609): <asynchronous suspension>
E/flutter (10609): #5      SimpleMutex.lock.<anonymous closure> (package:sqlite_async/src/mutex.dart:71:16)
E/flutter (10609): <asynchronous suspension>
E/flutter (10609): #6      SqliteConnectionImpl.writeLock (package:sqlite_async/src/sqlite_connection_impl.dart:114:12)
E/flutter (10609): <asynchronous suspension>
E/flutter (10609): #7      SqliteMigrations.migrate (package:sqlite_async/src/sqlite_migrations.dart:93:5)
E/flutter (10609): <asynchronous suspension>
E/flutter (10609): #8      main (package:jldb/main.dart:20:2)
E/flutter (10609): <asynchronous suspension>
E/flutter (10609): 
`
I'm using 
`  sqlite3_flutter_libs: ^0.5.17
  sqlite_async: ^0.5.2
`
in my main.dart
` 
import 'package:sqlite_async/sqlite_async.dart';

final migrations = SqliteMigrations()
  ..add(SqliteMigration(1, (tx) async {
    await tx.execute(
        'CREATE TABLE test_data(id INTEGER PRIMARY KEY AUTOINCREMENT, data TEXT)');
  }));

void main() async {

  final db = SqliteDatabase(path: 'test.db');

  await migrations.migrate(db);
  print("migrations returned");

  await db.executeBatch('INSERT INTO test_data(data) values(?)', [
    ['Test1'],
    ['Test2']
  ]);

  var results = await db.getAll('SELECT * FROM test_data');
  print('Results: $results');

  await db.close();

  runApp(MyApp());
}
`

**Comment by rkistner** [comment]
It's most likely related to the path that defaults to the current working directory, which won't be writable on Android. Try adding path_provider as a dependency, and using it to get the database path:

```dart
import 'package:flutter/material.dart';
import 'package:sqlite_async/sqlite_async.dart';
import 'package:path_provider/path_provider.dart';
import 'package:path/path.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized(); // Must be called if using path_provider before runApp()
  final dir = await getApplicationSupportDirectory();
  final path = join(dir.path, 'test.db');
  final db = SqliteDatabase(path: path);
  // ...
}
```

I'll make a note to update the examples to include this.

**Comment by tiwwwi** [comment]
I confirm that this works!  thank!
